name: "Gist Sync File"
description: "Syncs between a local file and a gist"
inputs:
  gistPat:
    description: "personal access token with read/write access for the gist"
    required: true
  gistId:
    description: "id of the gist"
    required: true
  action:
    description: 'action to perform, either "upload" or "download"'
    required: true
  filename:
    description: "name of the file containing the content to upload or download"
    required: true
outputs:
  filename:
    description: "name of the local file containing the content to upload or download"
runs:
  using: "node16"
  main: "dist/index.js"
