name: "Gist Sync File"
description: "Creates, updates, deletes or downloads a file from a gist"
inputs:
  gistPat:
    description: "personal access token with read/write access for the gist"
    required: true
  gistId:
    description: "id of the gist - only required for delete, update and download"
    required: false
  action:
    description: 'action to perform, either "create", "delete", "update" or "download"'
    required: true
  filename:
    description: "name of the file containing the content to upload or download"
    required: true
outputs:
  fileContent:
    description: "content of the file for download and update actions"
  gistId:
    description: "id of the gist for create action"
runs:
  using: "node16"
  main: "dist/index.js"
